required-players: 4
max-players: 10
countdown-seconds: 45
lobby-spawn: 
  world: 'hypixelhub'
  x: 189
  y: 64
  z: 4
  pitch: 1
  yaw: 90
lobby-npc-spawn:
  world: 'hypixelhub'
  x: 10.5
  y: 80
  z: 25.5
  pitch: 0
  yaw: -90
arenas:
  '0':
    red-spawn:
      world: 'bhMap'
    blue-spawn:
      world: 'bhMap'
  #'1':
  #  red-spawn:
  #    world: 'world'
  #    x: 28
  #    y: 42
  #    z: 69
  #    pitch: 60
  #    yaw: 60
  #  blue-spawn:
  #    world: 'world'
  #    x: 69
  #    y: 420
  #    z: 69
  #    pitch: 60
  #    yaw: 60
